version: 2

jobs:
  build:
    working_directory: ~/approve-pr-with-image

    docker:
      - image: circleci/node:12.16.3

    steps:
      - checkout

      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Run yarn install
          command: yarn install

      - run:
          name: Run build
          command: |
            yarn build:ci

      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cache/yarn

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
